[package]
name = "mesh-msg"
version = "0.1.0"
authors = ["Stephen Weeks <tene@allalone.org>"]
edition = "2018"

[dependencies]
mio = "0.6.16"
mio-extras = "2.0.5"
failure = "0.1.5"
slab = "0.4.2"
bytes = "0.4.11"
linefeed = "0.5.4"
crossbeam = "0.7.1"
ssh2 = "0.3.3"
